#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Generate `reports/detection-fingerprints.md` from `findings/fingerprints.json`.

The catalogue is data; the prose report is derived. Nothing in the report is hand-typed, so
the two can never drift — same rule as every other generated file in this repo.

Usage:
    uv run scripts/make_fingerprints.py
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "findings" / "fingerprints.json"
OUT = ROOT / "reports" / "detection-fingerprints.md"

POWER_MARK = {"high": "●●●", "medium": "●●○", "low": "●○○"}
EVIDENCE_LABEL = {
    "documented_catch": "someone really caught a bad provider this way",
    "literature_supported": "the underlying degradation is published; the catch is not",
    "plausible_untested": "reasoned out, no documented case",
}


def bullets(items: list[str]) -> str:
    return "\n".join(f"- {b}" for b in items)


def render_family(f: dict[str, Any]) -> str:
    lines = [
        f"### {f['id']} — {f['name']}",
        "",
        f"*{f['one_line']}*",
        "",
        "| | |",
        "| --- | --- |",
        f"| **Discriminative power** | {POWER_MARK[f['discriminative_power']]} "
        f"{f['discriminative_power']} |",
        f"| **Evidence** | `{f['evidence_strength']}` — {EVIDENCE_LABEL[f['evidence_strength']]} |",
        f"| **Needs raw outputs** | {'yes' if f['needs_raw_outputs'] else 'no'} |",
        f"| **Reveals** | {', '.join(f['related_mistake_ids']) or '—'} |",
        f"| **Citation status** | {f['verification']} |",
        "",
        f"**What you see.** {f['what_you_see']}",
        "",
        f"**Where to look.** {f['where_to_look']}",
        "",
        f"**Why routing produces it.** {f['mechanism']}",
        "",
        f"**How to check.** {f['how_to_check']}",
        "",
        "**Benign explanations — read these before concluding anything.**",
        "",
        bullets(f["benign_explanations"]),
        "",
    ]
    if f["real_instances"]:
        lines += ["**Documented instances.**", ""]
        for ri in f["real_instances"]:
            lines.append(f"- {ri['what_happened']}  \n  <{ri['url']}>")
            if ri["verbatim_quote"]:
                lines.append(f"  > {ri['verbatim_quote']}")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    if not SRC.exists():
        raise SystemExit(f"missing {SRC}")
    data = json.loads(SRC.read_text())
    fams = data["families"]
    prov = data["provenance"]

    n_high = sum(1 for f in fams if f["discriminative_power"] == "high")
    n_raw = sum(1 for f in fams if f["needs_raw_outputs"])
    n_caught = sum(1 for f in fams if f["evidence_strength"] == "documented_catch")

    out = [
        "# Fingerprints of bad inference, visible from the outside",
        "",
        "> Generated by `scripts/make_fingerprints.py` from "
        "[`findings/fingerprints.json`](../findings/fingerprints.json). Do not edit by hand.",
        "",
        data["about"],
        "",
        "## The bottom line",
        "",
        prov["headline"],
        "",
        f"**{len(fams)}** fingerprint families survived. **{n_high}** have high discriminative "
        f"power; **{n_caught}** rest on a documented catch rather than on inference; **{n_raw}** "
        "are checkable only when the authors released raw outputs.",
        "",
        "## How this was built",
        "",
        prov["method"],
        "",
        f"- raw candidates: **{prov['raw_candidates']}** from independent search angles",
        f"- adversarially verified: **{prov['verified_candidates']}**, of which "
        f"**{prov['survived_verification']}** survived",
        f"- not verified: **{prov['unverified_candidates']}**",
        "",
        prov["verification_note"],
        "",
        "## Reader's checklist",
        "",
        "Cheapest and highest-yield first.",
        "",
        "\n".join(f"{i}. {c}" for i, c in enumerate(data["reader_checklist"], 1)),
        "",
        "## What you cannot tell, and why",
        "",
        "This is a first-class result, not a caveat. Quantization is engineered to be subtle, and "
        "the reporting conventions of the field destroy most of the signal before publication.",
        "",
        bullets(data["undetectable"]),
        "",
        "## The families",
        "",
        "| id | fingerprint | power | needs raw outputs |",
        "| --- | --- | --- | --- |",
    ]
    for f in fams:
        # Plain ids, not anchors: family names carry em dashes and commas that GitHub's
        # slugger mangles, and a broken anchor is worse than no anchor.
        out.append(
            f"| **{f['id']}** | {f['name']} | {f['discriminative_power']} "
            f"| {'yes' if f['needs_raw_outputs'] else 'no'} |"
        )
    out += [""]
    for f in fams:
        out.append(render_family(f))

    OUT.write_text("\n".join(out).rstrip() + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(fams)} families, {OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
