#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Regenerate reports/prior-work.md from the curated list and the fetched sources.

Nothing in the generated file is hand-typed: titles, authors and dates for papers come from
the arXiv API snapshot, and every quotation was located verbatim in the fetched abstract or
page text. Entries nobody has independently checked are printed in a separate leads section
and never given a quote, so an unchecked lead can never read as sourced evidence.

Run:  uv run scripts/fetch_prior_work_sources.py   # refresh the snapshot first
      uv run scripts/make_prior_work.py
Out:  reports/prior-work.md
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "findings/prior_work.json"
SNAP = ROOT / "findings/prior_work_sources.json"
OUT = ROOT / "reports/prior-work.md"

TIER_ORDER = {"direct": 0, "adjacent": 1}
KIND_LABEL = {"paper": "paper", "post": "post", "vendor": "vendor statement", "docs": "vendor docs",
              "policy": "benchmark-org policy", "incident": "incident", "issue": "issue/PR"}


def authors(names: list[str]) -> str:
    if len(names) <= 3:
        return ", ".join(names)
    return ", ".join(names[:3]) + " et al."


def title_of(e: dict, snap: dict) -> str:
    rec = snap.get(e["key"], {})
    return rec.get("title") or e.get("title") or e["key"]


def url_of(e: dict, snap: dict) -> str:
    rec = snap.get(e["key"], {})
    if rec.get("kind") == "arxiv":  # unversioned, so the link does not go stale on a revision
        return f"https://arxiv.org/abs/{rec['arxiv_id']}"
    return e.get("url", "")


def byline(e: dict, snap: dict) -> str:
    rec = snap.get(e["key"], {})
    if rec.get("kind") == "arxiv":
        date = rec["published"] if rec["published"] == rec["updated"] else f"{rec['published']}, rev. {rec['updated']}"
        return f"{authors(rec['authors'])} · {e.get('venue', 'preprint')} · arXiv:{rec['arxiv_id']} · {date}"
    bits = [b for b in (e.get("author"), e.get("outlet"), e.get("date")) if b]
    return " · ".join(bits)


def main() -> None:
    data = json.loads(SRC.read_text())
    snapshot = json.loads(SNAP.read_text())
    snap = snapshot["sources"]
    entries = data["entries"]

    for e in entries:
        if e.get("verified") and e["key"] not in snap:
            raise SystemExit(f"{e['key']} is marked verified but is missing from {SNAP.name} — "
                             "run scripts/fetch_prior_work_sources.py.")
        if not e.get("verified") and e.get("quote"):
            raise SystemExit(f"{e['key']} is an unverified lead but carries a quote — "
                             "verify it (add it to the fetch run) or drop the quote.")

    # `rank` is the curated display order: strongest evidence first within each tier.
    verified = sorted([e for e in entries if e.get("verified")],
                      key=lambda e: (TIER_ORDER.get(e["tier"], 9), e["rank"]))
    leads = sorted([e for e in entries if not e.get("verified")],
                   key=lambda e: (TIER_ORDER.get(e["tier"], 9), e["rank"]))
    new = [e for e in verified if e["status"] == "new"]

    L: list[str] = []
    L.append("# Prior work — who has already documented this, and how well\n")
    L.append("<!-- GENERATED by scripts/make_prior_work.py from findings/prior_work.json + "
             "findings/prior_work_sources.json. Do not edit by hand. -->\n")
    L.append("This survey's claim — that a model slug behind a multi-provider router is not a fixed "
             "artifact, so unpinned routing can corrupt a research result — is not novel, and the file "
             "exists to say exactly how much of it was already established and by whom.\n")
    L.append(f"**{len(verified)} sources verified, {len(new)} of them new to this repo. "
             f"{len(leads)} further leads are recorded but unchecked.**\n")
    L.append("Every quotation below was located verbatim in the source itself: abstracts come from the "
             "arXiv API, web quotes were found in the live page text, and both are pinned in "
             "`findings/prior_work_sources.json` with surrounding context. Titles, authors and dates for "
             "papers are fetched, never typed. Items in *Unchecked leads* were surfaced by a search agent "
             "and confirmed by nobody — they carry no quotation and must not be cited as evidence until "
             "someone verifies them.\n")
    L.append("`Supports` maps each source to the mistake codes in "
             "[`findings/taxonomy.md`](../findings/taxonomy.md).\n")
    L.append("---\n")

    last_tier = None
    for e in verified:
        if e["tier"] != last_tier:
            last_tier = e["tier"]
            heading = ("## Direct evidence\n" if last_tier == "direct"
                       else "## Adjacent evidence\n")
            L.append(heading)
        flag = " *(already cited in this repo)*" if e["status"] == "already-cited" else ""
        L.append(f"### [{title_of(e, snap)}]({url_of(e, snap)}){flag}\n")
        L.append(f"*{KIND_LABEL.get(e['kind'], e['kind'])} — {byline(e, snap)}*\n")
        L.append(f"> {e['quote']}")
        if e.get("quote_attribution"):
            L.append(f">\n> — {e['quote_attribution']}")
        L.append("")
        L.append(f"{e['why']}\n")
        L.append(f"`Supports: {', '.join(e['supports'])}`\n")

    L.append("---\n")
    L.append("## Unchecked leads\n")
    L.append("Surfaced by search, not verified by anyone here. Listed so the search does not have to be "
             "repeated, and so nobody mistakes an unchecked lead for a source.\n")
    L.append("| Lead | Where | Tier | Why it might matter |")
    L.append("|---|---|---|---|")
    for e in leads:
        where = " ".join(x for x in (e.get("outlet", ""), e.get("date", "")) if x)
        link = f"[{e.get('title', e['key'])}]({e['url']})" if e.get("url") else e.get("title", e["key"])
        if e.get("arxiv_id"):
            link = f"[{e.get('title', e['key'])}](https://arxiv.org/abs/{e['arxiv_id']})"
            where = f"arXiv:{e['arxiv_id']} {e.get('venue', '')}".strip()
        why = e["why"].replace("|", "\\|")
        L.append(f"| {link} | {where} | {e['tier']} | {why} |")
    L.append("")

    L.append("---\n")
    L.append(f"*Sources fetched {snapshot['fetched_at']}. Regenerate with "
             "`uv run scripts/fetch_prior_work_sources.py && uv run scripts/make_prior_work.py`; "
             "the fetch step fails loudly if a quotation can no longer be found at its source.*")

    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(verified)} verified, {len(leads)} leads")


if __name__ == "__main__":
    main()
