#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Regenerate reports/provider-transparency.md from the curated audit and its snapshots.

Nothing in the generated file is hand-typed. Quotations come from findings/
provider_transparency.json and are printed only when the fetched page snapshot confirms
them verbatim; the endpoint statistics come from our own measurement against OpenRouter's
API. Entries nobody independently checked are printed in a separate leads section, never
quoted, and never allowed to read as evidence — the same rule reports/prior-work.md follows.

Run:  uv run scripts/fetch_provider_transparency.py    # refresh the snapshots first
      uv run scripts/make_provider_transparency.py
Out:  reports/provider-transparency.md
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "findings/provider_transparency.json"
SNAP = ROOT / "findings/provider_transparency_sources.json"
OUT = ROOT / "reports/provider-transparency.md"

AXIS_LABEL = {"A": "serves-now", "B": "when-it-changed", "C": "what-happens-next"}


def axes_badge(axes: list[str]) -> str:
    if not axes:
        return "—"
    return ", ".join(f"**{a}** {AXIS_LABEL[a]}" for a in sorted(axes))


def main() -> None:
    data = json.loads(SRC.read_text())
    snapshot = json.loads(SNAP.read_text())
    sources, measured = snapshot["sources"], snapshot["measured"]
    entries = data["entries"]

    for e in entries:
        if not e.get("verified") and e.get("quotes"):
            raise SystemExit(f"{e['key']} is an unchecked lead but carries a quote — "
                             "verify it (add it to the fetch run) or drop the quote.")
        if e.get("verified") and e["key"] not in sources:
            raise SystemExit(f"{e['key']} is marked verified but has no page snapshot — "
                             "run scripts/fetch_provider_transparency.py.")

    verified = sorted([e for e in entries if e.get("verified")], key=lambda e: e["rank"])
    leads = sorted([e for e in entries if not e.get("verified")], key=lambda e: e["rank"])

    L: list[str] = []
    w = L.append

    w("# Provider transparency — who tells you when they change how they serve a model")
    w("")
    w("<!-- GENERATED by scripts/make_provider_transparency.py from "
      "findings/provider_transparency.json + findings/provider_transparency_sources.json. "
      "Do not edit by hand. -->")
    w("")
    w("The rest of this project asks whether *researchers* pin their provider routing. This "
      "file asks the mirror-image question: if a researcher wanted to do the right thing by "
      "reading the vendor's own disclosures, **could they?** When a provider changes the "
      "precision, the context cap, the inference engine, or the weights behind a model ID, "
      "does it say so anywhere a caller could find, in a dated form?")
    w("")
    w("Mostly not. And the way it fails is specific enough to be useful.")
    w("")
    w("## Three different things \"transparent\" can mean")
    w("")
    w("Providers that look comparable on a marketing page turn out to occupy different axes "
      "entirely, and a provider strong on one is routinely silent on another:")
    w("")
    w("| Axis | The question it answers |")
    w("| --- | --- |")
    for k, v in data["_axes"].items():
        head, _, tail = v.partition(" - ")
        w(f"| **{k}** — {AXIS_LABEL[k]} | {tail or head} |")
    w("")
    w(f"**{len(verified)} providers were verified against the live page; {len(leads)} are "
      f"unchecked leads.** Every quotation below was located verbatim in a snapshot of the "
      f"cited page taken by `scripts/fetch_provider_transparency.py`. The leads were "
      f"surfaced by one pass of search agents and confirmed by nobody; they carry no "
      f"quotation and must not be cited as evidence until someone verifies them. This is a "
      f"much thinner evidence base than [`prior-work.md`](prior-work.md) and should be read "
      f"as a map of where to look, not a finished audit.")
    w("")
    w("---")
    w("")
    w("## Verified")
    w("")

    for e in verified:
        w(f"### {e['provider']}")
        w("")
        w(f"*[{e['url']}]({e['url']}) · discloses on: {axes_badge(e['axes'])}*")
        w("")
        confirmed = {q["quote"] for q in sources[e["key"]]["quotes"] if q["confirmed"]}
        for q in e.get("quotes", []):
            if q in confirmed:
                w(f"> {q}")
                w(">")
        if e.get("quotes"):
            L[-1] = ""  # drop the trailing blockquote spacer
        if e.get("quote_exempt"):
            w(f"*{e['quote_exempt']}*")
            w("")
        w(e["note"])
        w("")
        w(f"**Gap:** {e['gap']}")
        w("")

    w("---")
    w("")
    w("## Unchecked leads")
    w("")
    w("Reported by a search agent, not verified. No quotations, by construction.")
    w("")
    for e in leads:
        w(f"- **{e['provider']}** — [docs]({e['url']}) · {axes_badge(e['axes'])}  ")
        w(f"  {e['note']}")
    w("")
    w("---")
    w("")
    w("## The one number that is ours")
    w("")
    w("Everything above is vendor testimony — the weakest evidence class this project "
      "recognises. So we measured the thing vendors cannot spin: whether they declare a "
      "quantization to OpenRouter at all.")
    w("")
    w(f"Across **{measured['endpoints_total']} serving endpoints** for "
      f"{len(measured['sample_models'])} widely-served open-weight models, "
      f"**{measured['undeclared_pct']}% ({measured['undeclared_count']}) declare no "
      f"quantization** — the field comes back `unknown`.")
    w("")
    w("| Declared quantization | Endpoints |")
    w("| --- | --- |")
    for q, n in measured["by_quantization"].items():
        label = "*(undeclared)*" if q == "undeclared" else f"`{q}`"
        w(f"| {label} | {n} |")
    w("")
    silent = measured["providers_always_undeclared"]
    w(f"**{len(silent)} providers declared nothing across the entire sample:** "
      + ", ".join(silent) + ".")
    w("")
    w(f"{len(measured['providers_declaring_somewhere'])} declared a real precision "
      f"somewhere: " + ", ".join(measured["providers_declaring_somewhere"]) + ".")
    w("")
    w("Sample: " + ", ".join(f"`{m}`" for m in measured["sample_models"]) + ".")
    w("")
    w("---")
    w("")
    w("## What the sweep actually found")
    w("")
    w("**Nobody logs the mutation.** Providers announce launches and they announce "
      "retirements. Almost none publish a dated record of a serving-config change to an "
      "endpoint that continues to exist under the same name — which is precisely the event "
      "that silently invalidates a research result, because nothing in the caller's code "
      "changes. Cloudflare's git-tracked catalog is the one place where such a change is "
      "reconstructible, and it is an accident of publishing the catalog as source rather "
      "than a deliberate disclosure.")
    w("")
    w("**The two strengths are held by disjoint sets of providers.** The hyperscalers and "
      "first-party labs are excellent on lifecycle — dated snapshot IDs, quantified notice "
      "periods, retirement tables — and *never* state serving precision. The GPU clouds are "
      "the reverse: several publish precision per model, and few can tell you when it last "
      "changed. No provider verified here does both well.")
    w("")
    w("**Vendor testimony contradicts itself often enough to need ranking.** Two of the "
      "leads below are cases where a provider's marketing claim and its own engineers' "
      "statements disagree about serving precision. This is the concrete reason this "
      "project ranks our measurement above independent prior work above vendor assertion.")
    w("")
    w("## What this means for the guidance")
    w("")
    w("**No provider changelog is a substitute for recording the endpoint yourself.** Even "
      "the best-documented provider gives a caller a point-in-time spec, not a diffable "
      "history, and the majority give nothing at all. The practice the skill should "
      "recommend is therefore unchanged by anything in this file: pin the provider, and "
      "snapshot `/api/v1/models/{slug}/endpoints` at run time alongside the results, so the "
      "serving config is recorded in *your* artifact rather than trusted to the vendor's.")
    w("")
    w("Two findings do sharpen the guidance:")
    w("")
    w("- **A written weight-fixity guarantee exists and is worth asking for.** Azure states "
      "it as a lifecycle contract and ships `versionUpgradeOption: NoAutoUpgrade` to enforce "
      "it. That is a hard pin, not a floor, and it is the shape other vendors should be "
      "held to.")
    w("- **A pinnable ID is not universal.** DeepSeek's API exposes only floating names, so "
      "for that provider there is no correct configuration to recommend — only measurement "
      "after the fact.")
    w("")

    OUT.write_text("\n".join(L).rstrip() + "\n")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(verified)} verified, {len(leads)} leads)")


if __name__ == "__main__":
    main()
